!include cloud.puml

!procedure Cloud($alias=cloud, $name="Cloud", $url="https://api.mobilispect.com")
    System($alias, $name, $url, $sprite = cloud)
!end procedure

!procedure TransitLand()
    Cloud($alias=transitland, $name="transitland", $url="https://transit.land/api/v2")
!end procedure

!unquoted procedure Layer($alias, $label, $tags="", $link="")
Boundary($alias, $label, "Layer", $tags, $link)
!endprocedure
