@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include common.puml

title System Context Diagram

System(mobile, "Mobilispect Mobile")

Cloud()
TransitLand()

Rel(mobile, cloud, "")
BiRel(mobile, transitland, "Routes, ...")
@enduml

