[versions]
kotlin = "1.8.20"
kotlinxCoroutines = "1.6.4"
kotlinxSerializationCSV = "2.0.0"
kotlinxSerialization = "1.5.0"
springBoot = "3.0.6"
springDependency = "1.1.0"
springDoc = "2.1.0"
squareSortDependency = "0.2"

[libraries]

kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }

# Serialization
kotlinx-serialization-csv = { module = "de.brudaswen.kotlinx.serialization:kotlinx-serialization-csv", version.ref = "kotlinxSerializationCSV" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# View OpenAPI
springdoc-openapi-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springDoc" }

[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency = { id = "io.spring.dependency-management", version.ref = "springDependency" }

square-sortDependencies = { id = "com.squareup.sort-dependencies", version.ref = "squareSortDependency" }
