[versions]
kotlin = "1.9.21"
kotlinxCoroutines = "1.7.3"
kotlinxSerializationCSV = "2.0.0"
kotlinxSerialization = "1.6.1"
resilience4j = "2.1.0"
springBoot = "3.1.5"
springDependency = "1.1.4"
springDoc = "2.2.0"
springDocPlugin = "1.8.0"
squareSortDependency = "0.4"

[libraries]

kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }

# Serialization
kotlinx-serialization-csv = { module = "de.brudaswen.kotlinx.serialization:kotlinx-serialization-csv", version.ref = "kotlinxSerializationCSV" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# Fault Tolerance
resilience4j-spring = { module = "io.github.resilience4j:resilience4j-spring-boot2", version.ref = "resilience4j" }

# View OpenAPI
springdoc-openapi-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springDoc" }

[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency = { id = "io.spring.dependency-management", version.ref = "springDependency" }

# Allow Generation of OpenAPI Schema
springdoc-openapi = { id = "org.springdoc.openapi-gradle-plugin", version.ref = "springDocPlugin" }

square-sortDependencies = { id = "com.squareup.sort-dependencies", version.ref = "squareSortDependency" }

