@startuml
skinparam linetype ortho

entity "Feeds\n GTFS, GTFS-RT" as feeds
entity "Feed Versions" as versions
entity "Scheduled Trips" as strips
entity "Scheduled Stops" as sstops
entity "Recorded Trips" as rtrips
entity "Recorded Stops" as rstops

' maybe match taxibus and regular together
Regions ||..|{ Agencies
Agencies ||..|{ Routes
Routes ||..|{ strips
strips ||..|{ sstops: stops at
rtrips ||..|{ rstops: stops at
feeds ||..|{ versions

Agencies }|..|| versions: GTFS
Routes }|..|{ versions: GTFS
strips ||..|| versions: GTFS
sstops ||..|| versions: GTFS
rtrips ||..|| versions: GTFS-RT
rstops ||..|| versions: GTFS-RT

@enduml