apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mobilispect-api
  annotations:
    networking.gke.io/managed-certificates: managed-cert
    networking.gke.io/v1beta1.FrontendConfig: mobilispect-frontend
    kubernetes.io/ingress.global-static-ip-name: "mobilispect-network"
spec:
  ingressClassName: "gce"
  rules:
    - host: api.mobilispect.com
      http:
        paths:
          - backend:
              service:
                name: mobilispect-api
                port:
                  number: 80
            path: "/"
            pathType: Prefix
