apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- managed-cert.yaml
- parallelstorecsi-mount.yaml

patches:
- path: version.yaml
- path: replicas.yaml
- path: settings.yaml
- path: env.yaml
- path: ingress.yaml
