apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - managed-cert.yaml

patchesStrategicMerge:
  - version.yaml
  - replicas.yaml
  - settings.yaml
  - env.yaml
  - ingress.yaml
