---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilispect-api
spec:
  template:
    spec:
      containers:
        - name: mobilispect-api
          image: northamerica-northeast1-docker.pkg.dev/mobilispect/mobilispect-api/mobilispect-api:0.0.10
