name: API

on:
  push:
    branches: [ "mobile" ]
  pull_request:

defaults:
  run:
    working-directory: api

jobs:
  gradle-verify:
    runs-on: ubuntu-22.04
    name: "Verify Gradle"
    steps:
      - uses: actions/checkout@v3

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.5
        with:
          min-wrapper-count: 1
          allow-snapshots: false
          allow-checksums: false

  analysis:
    runs-on: ubuntu-22.04
    name: "Static Analysis"
    needs: gradle-verify
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run detekt
        run: ./gradlew detekt

      - name: Upload detekt report
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: build/reports/detekt/detekt.sarif

  build:
    runs-on: ubuntu-22.04
    name: "Build"
    needs: gradle-verify
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: 'build/reports/tests'