name: Backend (CI)

on:
  push:
    branches: [ "mobile" ]
    paths:
      - '.github/workflows/backend-*.yml'
      - 'backend/**'
  pull_request:
    paths:
      - '.github/workflows/backend-*.yml'
      - 'backend/**'

defaults:
  run:
    working-directory: backend

jobs:
  gradle-verify:
    runs-on: ubuntu-22.04
    name: "Verify Gradle"
    steps:
      - uses: actions/checkout@v4

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.1.0
        with:
          min-wrapper-count: 1
          allow-snapshots: false
          allow-checksums: false

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Verify Dependency Order
        run: ./gradlew checkSortDependencies

  analysis:
    runs-on: ubuntu-22.04
    name: "Static Analysis"
    needs: gradle-verify
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run detekt with reviewdog
        uses: alaegin/Detekt-Action@v1.23.4
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: backend/config/detekt/detekt.yml

      - name: Generate SBOM
        run: ./gradlew cyclonedxBom

      - name: Upload SBOM
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 'sbom'
          path: 'backend/build/reports/bom.json'

  build:
    runs-on: ubuntu-22.04
    name: "Build"
    needs: gradle-verify
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Protocol Buffer Compiler
        uses: arduino/setup-protoc@v2.1.0
        with:
          version: 25.1
      
      - name: Build
        run: ./gradlew assemble

  test:
    runs-on: ubuntu-22.04
    name: "Test"
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Protocol Buffer Compiler
        uses: arduino/setup-protoc@v2.1.0
        with:
          version: 25.1
      
      - name: Setup transit-land.properties
        run: cp ./src/main/resources/transit-land.sample.properties ./src/test/resources/transit-land.properties

      - name: Run tests
        run: ./gradlew test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 'test-results'
          path: 'backend/build/reports/tests'

      - name: Run mutation tests
        uses: alandovskis/gradle-pitest-comment-action@e372e00fccf3117a423e8add38160b919f0b87e0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          reports-retention: 1
          reports-path: "backend/build/reports/pitest"
          reports-name: "mutation-results"
          working-directory: backend
