name: Backend (CI)

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/backend-*.yml'
      - 'backend/**'
  pull_request:
    paths:
      - '.github/workflows/backend-*.yml'
      - 'backend/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: backend

jobs:
  gradle-verify:
    runs-on: ubuntu-22.04
    name: "Verify Gradle"
    steps:
      - uses: actions/checkout@v4

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3
        with:
          min-wrapper-count: 1
          allow-snapshots: false
          allow-checksums: false

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Verify Dependency Order
        run: ./gradlew checkSortDependencies

  analysis:
    runs-on: ubuntu-22.04
    name: "Static Analysis"
    needs: gradle-verify
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run detekt with reviewdog
        uses: alaegin/Detekt-Action@v1.23.6
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: backend/config/detekt/detekt.yml

  build:
    runs-on: ubuntu-22.04
    name: "Build"
    needs: gradle-verify
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Setup Protocol Buffer Compiler
        uses: arduino/setup-protoc@v3.0.0
        with:
          version: 25.1
      
      - name: Build
        run: ./gradlew assemble

  test:
    runs-on: ubuntu-22.04
    name: "Test"
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Setup Protocol Buffer Compiler
        uses: arduino/setup-protoc@v3.0.0
        with:
          version: 25.1
      
      - name: Setup transit-land.properties
        run: cp ./src/main/resources/transit-land.sample.properties ./src/test/resources/transit-land.properties

      - name: Run tests
        run: ./gradlew test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 'test-results'
          path: 'backend/build/reports/tests'