name: CI

on:
  push:
    branches: [ "main", "mobile" ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
        with:
          min-wrapper-count: 1
          allow-snapshots: false
          allow-checksums: false

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run detekt
        run: ./gradlew android:detekt

      - name: Check lint
        run: ./gradlew android:lintDebug
        if: always()

      - name: Build Android APKs
        run: ./gradlew android:assemble

      - name: Run Android local tests
        run: ./gradlew android:test

      - name: Upload detekt report
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: android/build/reports/detekt/detekt.sarif

      - name: Upload lint report
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: android/build/reports/lint-results-debug.sarif
